import datetime
import os
import glob


def get_non_empty(prompt: str) -> str:
    value = input(prompt).strip()
    if not value:
        raise ValueError(f"Value for '{prompt}' cannot be empty.")
    return value


# -------------------------------------------------------------------
# SECTION: Metadata header
# -------------------------------------------------------------------
def generate_header(device: str, mode: str):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = f"""!
! GOLDEN CONFIG generated by Cisco Micro-Tool Generator
! Mode: {mode.upper()}
! Device: {device}
! Date: {now}
!
"""
    return header


# -------------------------------------------------------------------
# SECTION: Built-in baseline components
# -------------------------------------------------------------------
def generate_banner():
    return """
banner login ^
Unauthorized access prohibited.
All actions are logged.
^
"""


def generate_logging():
    return """
! Logging baseline
service timestamps debug datetime localtime
service timestamps log datetime localtime
logging buffered 64000 warnings
logging console warnings
"""


def generate_security_baseline(mode: str):
    base = """
! Security baseline
no ip http server
no ip http secure-server
ip ssh version 2
ip ssh authentication-retries 3
ip ssh time-out 60
"""

    if mode == "secure":
        base += """
ip ssh source-interface Loopback0
ip ssh cipher aes256-ctr
ip ssh key-exchange group14-sha256
"""

    if mode == "hardened":
        base += """
ip ssh cipher aes256-ctr aes192-ctr aes128-ctr
ip ssh key-exchange group16-sha512
ip ssh key-exchange group14-sha256
no cdp run
no lldp run
"""

    return base


# -------------------------------------------------------------------
# SECTION: Auto-detect module config files
# -------------------------------------------------------------------
def auto_detect_modules():
    files = []

    for pattern in [
        "snmpv3_config*.txt",
        "snmpv3_config*.cfg",
        "ntp_config*.txt",
        "aaa_tacacs*.txt",
        "aaa_tacacs*.cfg",
    ]:
        found = glob.glob(pattern)
        files.extend(found)

    return files


def load_file(path: str) -> str:
    try:
        with open(path, "r") as f:
            return f.read()
    except Exception:
        return f"\n! ERROR: Could not load {path}\n"


# -------------------------------------------------------------------
# SECTION: Oneline converter
# -------------------------------------------------------------------
def to_oneline(block: str) -> str:
    out = []
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("!"):
            continue
        out.append(line)
    return " ; ".join(out)


# -------------------------------------------------------------------
# MAIN
# -------------------------------------------------------------------
def main():
    print("=== Golden Config Generator v0.2 ===\n")

    device = input("Device type (default: Cisco IOS XE): ").strip() or "Cisco IOS XE"

    mode = input("Mode (standard / secure / hardened) [standard]: ").strip().lower() or "standard"
    if mode not in ["standard", "secure", "hardened"]:
        raise ValueError("Invalid mode. Choose: standard, secure, hardened")

    output_format = input("Output format (cli / oneline) [cli]: ").strip().lower() or "cli"

    print("\nAuto-detecting module configs...")
    modules = auto_detect_modules()

    if not modules:
        print("\n[WARNING] No module config files found in current directory.\n")
    else:
        print("\nFound sections:")
        for m in modules:
            print(f" - {m}")

    golden = generate_header(device, mode)

    for section in modules:
        golden += f"\n\n! SECTION: {section}\n"
        golden += load_file(section)

    golden += "\n\n! Banner\n"
    golden += generate_banner()

    golden += "\n\n"
    golden += generate_logging()

    golden += "\n\n"
    golden += generate_security_baseline(mode)

    if output_format == "oneline":
        golden = to_oneline(golden) + "\n"

    export = input("\nExport to file? (y/n) [y]: ").strip().lower() or "y"

    if export == "y":
        filename = f"golden_config_{mode}.txt"
        with open(filename, "w") as f:
            f.write(golden)
        print(f"\nSaved to {filename}\n")
    else:
        print("\nGenerated Golden Config:\n")
        print(golden)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"\n[ERROR] {e}\n")
