import datetime


def get_non_empty(prompt: str) -> str:
    value = input(prompt).strip()
    if not value:
        raise ValueError(f"Value for '{prompt}' cannot be empty.")
    return value


def generate_header(device: str, mode: str):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = f"""!
! GOLDEN CONFIG generated by Cisco Micro-Tool Generator
! Mode: {mode}
! Device: {device}
! Date: {now}
!
"""
    return header


def generate_banner():
    banner = """
banner login ^
Unauthorized access to this device is prohibited.
All actions are monitored and logged.
^
"""
    return banner


def generate_logging():
    cfg = """
! Logging baseline
service timestamps debug datetime localtime
service timestamps log datetime localtime
logging buffered 64000 warnings
logging console warnings
"""
    return cfg


def generate_security_baseline():
    cfg = """
! Minimal security hardening baseline
no ip http server
no ip http secure-server
ip domain-lookup
ip ssh version 2
ip ssh authentication-retries 3
ip ssh time-out 60
!
"""
    return cfg


def load_section(path: str) -> str:
    try:
        with open(path, "r") as f:
            return f.read()
    except FileNotFoundError:
        print(f"[WARNING] Section file missing: {path}")
        return f"\n! Missing section: {path}\n"


def generate_oneline(block: str) -> str:
    lines = []
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("!"):
            continue
        lines.append(line)
    return " ; ".join(lines)


def main():
    print("=== Golden Config Generator v0.1 ===\n")

    device = input("Device type (default: Cisco IOS XE): ").strip() or "Cisco IOS XE"
    mode = input("Golden config mode (standard / secure) [standard]: ").strip() or "standard"

    output_format = input("Output format (cli / oneline) [cli]: ").strip() or "cli"

    # Paths to your module outputs (user can paste them from previous generators)
    print("\nPaste paths to existing config files (press Enter to skip):")
    snmp_path = input("SNMPv3 config file: ").strip()
    ntp_path = input("NTP config file: ").strip()
    aaa_path = input("AAA/TACACS+ config file: ").strip()

    full_config = generate_header(device, mode)

    # Load or skip modules
    if snmp_path:
        full_config += "\n\n! SNMPv3 section\n"
        full_config += load_section(snmp_path)

    if ntp_path:
        full_config += "\n\n! NTP section\n"
        full_config += load_section(ntp_path)

    if aaa_path:
        full_config += "\n\n! AAA / TACACS section\n"
        full_config += load_section(aaa_path)

    # Add built-in sections
    full_config += "\n\n! Banner\n"
    full_config += generate_banner()

    full_config += "\n\n"
    full_config += generate_logging()

    full_config += "\n\n"
    full_config += generate_security_baseline()

    # Output formatting
    if output_format == "oneline":
        final = generate_oneline(full_config)
    else:
        final = full_config

    export = input("\nExport to file? (y/n) [y]: ").strip().lower() or "y"
    if export == "y":
        filename = input("Filename (default: golden_config.txt): ").strip() or "golden_config.txt"
        with open(filename, "w") as f:
            f.write(final)
        print(f"\nSaved to file: {filename}\n")
    else:
        print("\nGenerated Golden Config:\n")
        print(final)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"\n[ERROR] {e}\n")
