import datetime


def get_non_empty(prompt: str) -> str:
    value = input(prompt).strip()
    if not value:
        raise ValueError(f"Value for '{prompt}' cannot be empty.")
    return value


def validate_server(server: str) -> str:
    # Minimal input validation – keep it simple for v0.1
    if " " in server:
        raise ValueError("NTP server cannot contain spaces.")
    return server


def generate_header(device: str):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = f"""!
! NTP config generated by Cisco Micro-Tool Generator
! Date: {now}
! Device: {device}
!
"""
    return header


def generate_ntp_cli(server1, server2, timezone, key_id=None, key_value=None):
    cfg = f"""
clock timezone {timezone}
ntp server {server1}
"""
    if server2:
        cfg += f"ntp server {server2}\n"

    if key_id and key_value:
        cfg += f"""
ntp authenticate
ntp authentication-key {key_id} md5 {key_value}
ntp trusted-key {key_id}
"""

    cfg += "\n!"
    return cfg


def generate_ntp_oneline(server1, server2, timezone, key_id=None, key_value=None):
    commands = [
        f"clock timezone {timezone}",
        f"ntp server {server1}",
    ]
    if server2:
        commands.append(f"ntp server {server2}")

    if key_id and key_value:
        commands.append("ntp authenticate")
        commands.append(f"ntp authentication-key {key_id} md5 {key_value}")
        commands.append(f"ntp trusted-key {key_id}")

    return " ; ".join(commands)


def main():
    print("=== NTP Config Generator v0.1 ===\n")

    device = input("Device type (default: Cisco IOS XE): ").strip() or "Cisco IOS XE"

    server1 = validate_server(get_non_empty("Primary NTP server: "))
    server2 = input("Secondary NTP server (optional): ").strip()
    if server2:
        server2 = validate_server(server2)

    timezone = get_non_empty("Timezone (e.g. UTC, CET, PST): ")

    use_auth = input("Use NTP authentication? (y/n): ").strip().lower()
    key_id = key_value = None

    if use_auth == "y":
        key_id = get_non_empty("Key ID (integer): ")
        key_value = get_non_empty("Key value (MD5 key): ")

    output_format = input("Output format (cli / oneline) [cli]: ").strip().lower() or "cli"

    if output_format not in ["cli", "oneline"]:
        raise ValueError("Invalid output format. Allowed: cli, oneline.")

    header = generate_header(device)

    if output_format == "cli":
        config = generate_ntp_cli(server1, server2, timezone, key_id, key_value)
    else:
        config = generate_ntp_oneline(server1, server2, timezone, key_id, key_value) + "\n"

    final_output = header + config + "\n"

    export = input("\nExport to file? (y/n): ").strip().lower()
    if export == "y":
        default_filename = "ntp_config.txt" if output_format == "cli" else "ntp_config_oneline.txt"
        filename = input(f"Filename (default: {default_filename}): ").strip() or default_filename
        with open(filename, "w") as f:
            f.write(final_output)
        print(f"\nSaved to file: {filename}\n")
    else:
        print("\nGenerated NTP configuration:\n")
        print(final_output)


if __name__ == "__main__":
    try:
        main()
    except ValueError as e:
        print(f"\n[ERROR] {e}")
        print("Aborting.\n")
