"""
Export router - PDF, JSON, and Markdown report generation
v0.4.6
"""

from fastapi import APIRouter, Query
from fastapi.responses import Response, JSONResponse, PlainTextResponse
from fpdf import FPDF
from datetime import datetime
from services.profile_service import ProfileService
from typing import Optional

router = APIRouter()
svc = ProfileService()


def generate_markdown_report(data: dict) -> str:
    """Generate markdown security report from data."""
    lines = []

    # Header
    lines.append("# NetDevOps Micro-Tools")
    lines.append("## Security Assessment Report")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"- **Report Date:** {data['timestamp'][:10]}")
    lines.append(f"- **Profiles Analyzed:** {data['profiles_checked']}")

    if data.get('average_score') is not None:
        lines.append(f"- **Average Security Score:** {data['average_score']:.1f}/100")
        lines.append(f"- **Lowest Score:** {data.get('lowest_score', 'N/A')}")
        lines.append(f"- **Highest Score:** {data.get('highest_score', 'N/A')}")

    lines.append("")

    # Summary table
    summary = data.get('summary', {})
    lines.append("### Score Distribution")
    lines.append("")
    lines.append("| Category | Count | Score Range |")
    lines.append("|----------|-------|-------------|")
    categories = [
        ("Excellent", summary.get('excellent', 0), "90-100"),
        ("Good", summary.get('good', 0), "70-89"),
        ("Fair", summary.get('fair', 0), "50-69"),
        ("Poor", summary.get('poor', 0), "25-49"),
        ("Critical", summary.get('critical', 0), "0-24"),
        ("Unknown", summary.get('unknown', 0), "N/A"),
    ]
    for cat, count, score_range in categories:
        lines.append(f"| {cat} | {count} | {score_range} |")

    lines.append("")

    # Profile Details
    lines.append("## Profile Details")
    lines.append("")

    for profile in data.get('results', []):
        name = profile.get('profile_name', 'Unknown')
        score = profile.get('score')
        label = profile.get('label', 'Unknown')
        platform = profile.get('platform', 'N/A')
        version = profile.get('version', 'N/A')
        cve_count = profile.get('cve_count', 0)

        score_str = f"{score}/100" if score is not None else "N/A"
        lines.append(f"### {name}")
        lines.append("")
        lines.append(f"- **Score:** {score_str} ({label})")
        lines.append(f"- **Platform:** {platform}")
        lines.append(f"- **Version:** {version}")
        lines.append(f"- **CVE Count:** {cve_count}")

        # CVE breakdown
        cve_breakdown = profile.get('cve_breakdown', [])
        if cve_breakdown:
            lines.append("")
            lines.append("| CVE ID | Severity | CVSS | Penalty | Modifiers |")
            lines.append("|--------|----------|------|---------|-----------|")
            for cve in cve_breakdown[:10]:
                cve_id = cve.get('cve_id', 'N/A')
                severity = cve.get('severity', 'N/A')
                cvss = cve.get('cvss_score')
                cvss_str = f"{cvss:.1f}" if cvss else "N/A"
                penalty = cve.get('final_penalty', 0)
                modifiers = ", ".join(cve.get('modifiers_applied', [])) or "None"
                lines.append(f"| {cve_id} | {severity} | {cvss_str} | -{penalty:.1f} | {modifiers} |")

            if len(cve_breakdown) > 10:
                lines.append(f"| ... | *{len(cve_breakdown) - 10} more CVEs* | | | |")

        lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by NetDevOps Micro-Tools | {data['timestamp']}*")

    return "\n".join(lines)


class SecurityReportPDF(FPDF):
    """Custom PDF class for security reports."""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "NetDevOps Micro-Tools", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, "Security Assessment Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Generated by NetDevOps Micro-Tools", align="C")

    def add_summary_section(self, data):
        """Add executive summary section."""
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

        self.set_font("Helvetica", "", 10)
        self.cell(0, 6, f"Report Date: {data['timestamp'][:10]}", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 6, f"Profiles Analyzed: {data['profiles_checked']}", new_x="LMARGIN", new_y="NEXT")

        if data.get('average_score') is not None:
            self.cell(0, 6, f"Average Security Score: {data['average_score']:.1f}/100", new_x="LMARGIN", new_y="NEXT")
            self.cell(0, 6, f"Lowest Score: {data.get('lowest_score', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
            self.cell(0, 6, f"Highest Score: {data.get('highest_score', 'N/A')}", new_x="LMARGIN", new_y="NEXT")

        self.ln(5)

        # Summary table
        summary = data.get('summary', {})
        self.set_font("Helvetica", "B", 10)
        self.cell(40, 8, "Category", border=1)
        self.cell(30, 8, "Count", border=1)
        self.cell(50, 8, "Score Range", border=1, new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 10)
        categories = [
            ("Excellent", summary.get('excellent', 0), "90-100"),
            ("Good", summary.get('good', 0), "70-89"),
            ("Fair", summary.get('fair', 0), "50-69"),
            ("Poor", summary.get('poor', 0), "25-49"),
            ("Critical", summary.get('critical', 0), "0-24"),
            ("Unknown", summary.get('unknown', 0), "N/A"),
        ]
        for cat, count, score_range in categories:
            self.cell(40, 7, cat, border=1)
            self.cell(30, 7, str(count), border=1)
            self.cell(50, 7, score_range, border=1, new_x="LMARGIN", new_y="NEXT")

        self.ln(10)

    def add_profile_section(self, profile):
        """Add individual profile section."""
        name = profile.get('profile_name', 'Unknown')
        score = profile.get('score')
        label = profile.get('label', 'Unknown')
        platform = profile.get('platform', 'N/A')
        version = profile.get('version', 'N/A')
        cve_count = profile.get('cve_count', 0)

        # Check if we need a new page
        if self.get_y() > 230:
            self.add_page()

        self.set_font("Helvetica", "B", 12)
        score_str = f"{score}/100" if score is not None else "N/A"
        self.cell(0, 8, f"Profile: {name} - Score: {score_str} ({label})", new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 10)
        self.cell(0, 6, f"Platform: {platform} | Version: {version} | CVEs: {cve_count}", new_x="LMARGIN", new_y="NEXT")

        # CVE breakdown table (if any CVEs)
        cve_breakdown = profile.get('cve_breakdown', [])
        if cve_breakdown:
            self.ln(3)
            self.set_font("Helvetica", "B", 9)
            self.cell(40, 7, "CVE ID", border=1)
            self.cell(25, 7, "Severity", border=1)
            self.cell(20, 7, "CVSS", border=1)
            self.cell(25, 7, "Penalty", border=1)
            self.cell(60, 7, "Modifiers", border=1, new_x="LMARGIN", new_y="NEXT")

            self.set_font("Helvetica", "", 8)
            for cve in cve_breakdown[:10]:  # Limit to 10 CVEs per profile
                cve_id = cve.get('cve_id', 'N/A')
                severity = cve.get('severity', 'N/A')
                cvss = cve.get('cvss_score')
                cvss_str = f"{cvss:.1f}" if cvss else "N/A"
                penalty = cve.get('final_penalty', 0)
                modifiers = ", ".join(cve.get('modifiers_applied', [])) or "None"

                self.cell(40, 6, cve_id[:18], border=1)
                self.cell(25, 6, severity, border=1)
                self.cell(20, 6, cvss_str, border=1)
                self.cell(25, 6, f"-{penalty:.1f}", border=1)
                self.cell(60, 6, modifiers[:25], border=1, new_x="LMARGIN", new_y="NEXT")

            if len(cve_breakdown) > 10:
                self.set_font("Helvetica", "I", 8)
                self.cell(0, 6, f"... and {len(cve_breakdown) - 10} more CVEs", new_x="LMARGIN", new_y="NEXT")

        self.ln(8)


@router.get("/export/security-report")
def export_security_report(format: Optional[str] = Query("pdf", description="Output format: pdf, json, or md")):
    """
    Generate security report for all profiles.

    Query params:
    - format: "pdf" (default), "json", or "md" (markdown)

    Returns:
    - PDF: downloadable file with executive summary and per-profile CVE details
    - JSON: raw data for programmatic access
    - Markdown: formatted text report
    """
    # Get security scores data
    scores_data = svc.calculate_all_security_scores()

    # Convert Pydantic model to dict
    data = scores_data.model_dump()

    # Add timestamp
    data['timestamp'] = datetime.utcnow().isoformat()

    # JSON format - return raw data
    if format == "json":
        return JSONResponse(content=data)

    # Markdown format
    if format in ("md", "markdown"):
        md_content = generate_markdown_report(data)
        filename = f"security-report-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}.md"
        return Response(
            content=md_content,
            media_type="text/markdown",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )

    # PDF format (default)
    pdf = SecurityReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # Add summary
    pdf.add_summary_section(data)

    # Add per-profile sections
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Profile Details", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    for profile in data.get('results', []):
        pdf.add_profile_section(profile)

    # Generate PDF bytes
    pdf_bytes = pdf.output()

    # Return as downloadable file
    filename = f"security-report-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}.pdf"
    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
