from fastapi import APIRouter
from pydantic import BaseModel
import datetime
from typing import Optional

router = APIRouter()


# --------------------------------------------------------------------
# REQUEST SCHEMA
# --------------------------------------------------------------------
class GoldenConfigRequest(BaseModel):
    device: str = "Cisco IOS XE"
    mode: str = "standard"       # standard | secure | hardened
    snmpv3_config: Optional[str] = None
    ntp_config: Optional[str] = None
    aaa_config: Optional[str] = None
    output_format: str = "cli"   # cli | oneline


# --------------------------------------------------------------------
# STATIC SECTIONS
# --------------------------------------------------------------------
def generate_banner():
    return """banner login ^
Unauthorized access to this device is prohibited.
All activity is monitored.
^
"""


def generate_logging():
    return """
! Logging baseline
service timestamps debug datetime localtime
service timestamps log datetime localtime
logging buffered 64000 warnings
logging console warnings
"""


def generate_security_baseline(mode: str):
    base = """
! Security baseline
no ip http server
no ip http secure-server
ip ssh version 2
ip ssh authentication-retries 3
ip ssh time-out 60
"""

    if mode == "secure":
        base += """
ip ssh cipher aes256-ctr
ip ssh key-exchange group14-sha256
"""

    if mode == "hardened":
        base += """
ip ssh cipher aes256-ctr aes192-ctr aes128-ctr
ip ssh key-exchange group16-sha512
ip ssh key-exchange group14-sha256
no cdp run
no lldp run
"""

    return base


# --------------------------------------------------------------------
# YAML TEMPLATE
# --------------------------------------------------------------------
def generate_golden_template(req: GoldenConfigRequest) -> str:
    """Generate YAML template for automation tools (Ansible, Netmiko, etc.)"""
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

    yaml = f"""# Golden Config YAML generated by NetDevOps Micro-Tools
# Mode: {req.mode}
# Date: {now}
# Device: {req.device}

golden_config:
  device: "{req.device}"
  mode: "{req.mode}"

  sections:
    snmpv3:
      enabled: {str(bool(req.snmpv3_config)).lower()}
      config: |
{_indent_multiline(req.snmpv3_config, 8) if req.snmpv3_config else "        # Not configured"}

    ntp:
      enabled: {str(bool(req.ntp_config)).lower()}
      config: |
{_indent_multiline(req.ntp_config, 8) if req.ntp_config else "        # Not configured"}

    aaa:
      enabled: {str(bool(req.aaa_config)).lower()}
      config: |
{_indent_multiline(req.aaa_config, 8) if req.aaa_config else "        # Not configured"}

  baseline:
    banner:
      enabled: true
      text: "Unauthorized access to this device is prohibited. All activity is monitored."

    logging:
      enabled: true
      buffer_size: 64000
      level: "warnings"
      timestamps: true

    security:
      http_server: false
      https_server: false
      ssh_version: 2
      ssh_auth_retries: 3
      ssh_timeout: 60
      cdp: {"false" if req.mode == "hardened" else "true"}
      lldp: {"false" if req.mode == "hardened" else "true"}
"""
    return yaml.strip()


def _indent_multiline(text: str, spaces: int) -> str:
    """Helper to indent multiline text for YAML"""
    if not text:
        return ""
    indent = " " * spaces
    lines = text.strip().split("\n")
    return "\n".join(indent + line for line in lines)


# --------------------------------------------------------------------
# ASSEMBLER
# --------------------------------------------------------------------
def assemble_golden(req: GoldenConfigRequest):
    sections = []

    # Provided configs
    if req.snmpv3_config:
        sections.append(f"! SNMPv3\n{req.snmpv3_config}")

    if req.ntp_config:
        sections.append(f"! NTP\n{req.ntp_config}")

    if req.aaa_config:
        sections.append(f"! AAA\n{req.aaa_config}")

    # Built-in sections
    sections.append("! Banner\n" + generate_banner())
    sections.append("! Logging\n" + generate_logging())
    sections.append("! Security\n" + generate_security_baseline(req.mode))

    final = "\n\n".join(sections)

    if req.output_format == "oneline":
        lines = []
        for line in final.splitlines():
            line = line.strip()
            if not line or line.startswith("!"):
                continue
            lines.append(line)
        final = " ; ".join(lines)

    return final


# --------------------------------------------------------------------
# API ENDPOINT
# --------------------------------------------------------------------
@router.post("/golden-config")
def generate_golden_config(req: GoldenConfigRequest):

    if req.output_format == "template":
        final_cfg = generate_golden_template(req)
    else:
        final_cfg = assemble_golden(req)

    return {
        "device": req.device,
        "mode": req.mode,
        "output_format": req.output_format,
        "config": final_cfg,
        "metadata": {
            "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
            "module": "Golden Config Builder",
            "tool": "NetDevOps Micro-Tools"
        }
    }
