from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional
import datetime

router = APIRouter()


# -----------------------------
# SNMPv3 Request Schema (v2)
# -----------------------------
class SNMPv3Request(BaseModel):
    # Basic settings
    mode: str = "secure-default"  # secure-default | balanced | legacy-compatible
    device: str = "Cisco IOS XE"
    host: str
    user: str
    group: str
    auth_password: str
    priv_password: str
    output_format: str = "cli"  # cli | oneline | template

    # v2: New fields
    access_mode: str = "read-only"  # read-only | read-write
    use_acl: bool = False
    acl_hosts: Optional[str] = None  # comma-separated IPs
    source_interface: Optional[str] = None  # e.g. Loopback0, GigabitEthernet0/0


# -----------------------------
# SNMPv3 Logic (API-adapted)
# -----------------------------
ALGORITHMS = {
    "secure-default": ("sha-2 256", "aes 256"),
    "balanced": ("sha", "aes 128"),
    "legacy-compatible": ("sha", "aes 128"),
}

# View names based on access mode
VIEW_NAMES = {
    "read-only": "SNMP-RO-VIEW",
    "read-write": "SNMP-RW-VIEW",
}


def generate_snmpv3_cli(user, group, mode, host, auth_pass, priv_pass,
                        access_mode="read-only", use_acl=False, acl_hosts=None,
                        source_interface=None):
    auth_algo, priv_algo = ALGORITHMS.get(mode, ("sha", "aes 128"))
    view_name = VIEW_NAMES.get(access_mode, "SNMP-RO-VIEW")

    sections = []

    # ACL section (if enabled)
    if use_acl and acl_hosts:
        acl_lines = ["!", "! SNMP Access Control List", "ip access-list standard SNMP-ACCESS"]
        hosts = [h.strip() for h in acl_hosts.split(",") if h.strip()]
        for i, host_ip in enumerate(hosts, 1):
            acl_lines.append(f"  permit {host_ip}")
        acl_lines.append("  deny any log")
        sections.append("\n".join(acl_lines))

    # View section
    sections.append(f"!\n! SNMP View\nsnmp-server view {view_name} iso included")

    # Group section
    acl_ref = " access SNMP-ACCESS" if use_acl and acl_hosts else ""
    if access_mode == "read-write":
        group_cmd = f"snmp-server group {group} v3 priv read {view_name} write {view_name}{acl_ref}"
    else:
        group_cmd = f"snmp-server group {group} v3 priv read {view_name}{acl_ref}"
    sections.append(f"!\n! SNMP Group ({access_mode})\n{group_cmd}")

    # User section
    user_cmd = f"snmp-server user {user} {group} v3 auth {auth_algo} {auth_pass} priv {priv_algo} {priv_pass}"
    sections.append(f"!\n! SNMP User\n{user_cmd}")

    # Host section
    host_cmd = f"snmp-server host {host} version 3 priv {user}"
    sections.append(f"!\n! SNMP Host\n{host_cmd}")

    # Source interface (if specified)
    if source_interface:
        sections.append(f"!\n! SNMP Source Interface\nsnmp-server trap-source {source_interface}")

    # Traps
    sections.append("!\n! SNMP Traps\nsnmp-server enable traps")

    return "\n".join(sections)


def generate_snmpv3_oneline(cli_text: str):
    lines = []
    for line in cli_text.splitlines():
        line = line.strip()
        if not line or line.startswith("!"):
            continue
        lines.append(line)
    return " ; ".join(lines)


def generate_snmpv3_template(user, group, mode, host, auth_pass, priv_pass, device,
                             access_mode="read-only", use_acl=False, acl_hosts=None,
                             source_interface=None):
    """Generate YAML template for automation tools (Ansible, Netmiko, etc.)"""
    auth_algo, priv_algo = ALGORITHMS.get(mode, ("sha", "aes 128"))
    view_name = VIEW_NAMES.get(access_mode, "SNMP-RO-VIEW")
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

    # Parse ACL hosts
    acl_list = []
    if use_acl and acl_hosts:
        acl_list = [h.strip() for h in acl_hosts.split(",") if h.strip()]

    yaml = f"""# SNMPv3 YAML config generated by NetDevOps Micro-Tools
# Mode: {mode}
# Access: {access_mode}
# Date: {now}
# Device: {device}

snmpv3_config:
  view:
    name: "{view_name}"
    oid: "iso"
    included: true

  group:
    name: "{group}"
    version: 3
    security_level: "priv"
    read_view: "{view_name}"
    write_view: {f'"{view_name}"' if access_mode == "read-write" else "null"}
    acl: {"SNMP-ACCESS" if use_acl and acl_list else "null"}

  users:
    - name: "{user}"
      group: "{group}"
      auth_algorithm: "{auth_algo}"
      auth_password: "{auth_pass}"
      priv_algorithm: "{priv_algo}"
      priv_password: "{priv_pass}"

  host:
    address: "{host}"
    version: 3
    security_level: "priv"
    user: "{user}"

  source_interface: {f'"{source_interface}"' if source_interface else "null"}

  acl:
    enabled: {str(use_acl and len(acl_list) > 0).lower()}
    name: "SNMP-ACCESS"
    permitted_hosts: {acl_list if acl_list else "[]"}

  traps:
    enabled: true
"""
    return yaml.strip()


# -----------------------------
# SNMPv3 API Endpoint (v2)
# -----------------------------
@router.post("/snmpv3")
def generate_snmpv3(req: SNMPv3Request):

    if req.output_format == "template":
        output = generate_snmpv3_template(
            user=req.user,
            group=req.group,
            mode=req.mode,
            host=req.host,
            auth_pass=req.auth_password,
            priv_pass=req.priv_password,
            device=req.device,
            access_mode=req.access_mode,
            use_acl=req.use_acl,
            acl_hosts=req.acl_hosts,
            source_interface=req.source_interface,
        )
    else:
        cli_config = generate_snmpv3_cli(
            user=req.user,
            group=req.group,
            mode=req.mode,
            host=req.host,
            auth_pass=req.auth_password,
            priv_pass=req.priv_password,
            access_mode=req.access_mode,
            use_acl=req.use_acl,
            acl_hosts=req.acl_hosts,
            source_interface=req.source_interface,
        )

        if req.output_format == "oneline":
            output = generate_snmpv3_oneline(cli_config)
        else:
            output = cli_config

    return {
        "mode": req.mode,
        "access_mode": req.access_mode,
        "device": req.device,
        "output_format": req.output_format,
        "config": output,
        "metadata": {
            "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
            "module": "SNMPv3 Generator v2",
            "tool": "NetDevOps Micro-Tools"
        }
    }
