import datetime

MODES = ["secure-default", "balanced", "legacy-compatible", "custom"]


def choose_mode():
    print("Available modes:")
    for m in MODES:
        print(f" - {m}")
    mode = input("Mode (secure-default / balanced / legacy-compatible / custom): ").strip().lower()

    if mode not in MODES:
        raise ValueError(f"Invalid mode: {mode}. Allowed: {', '.join(MODES)}")

    return mode


def get_non_empty(prompt: str) -> str:
    value = input(prompt).strip()
    if not value:
        raise ValueError(f"Value for '{prompt}' cannot be empty.")
    return value


def resolve_algorithms(mode: str):
    if mode == "secure-default":
        return "SHA-256", "AES-256"
    elif mode == "balanced":
        return "SHA", "AES-128"
    elif mode == "legacy-compatible":
        return "SHA", "AES-128"
    elif mode == "custom":
        auth_algo = get_non_empty("Auth algorithm (SHA/SHA-256/SHA-512): ")
        priv_algo = get_non_empty("Privacy algorithm (AES-128/AES-256): ")
        return auth_algo, priv_algo
    else:
        raise ValueError(f"Unsupported mode: {mode}")


def generate_header(mode: str, device: str):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = f"""!
! SNMPv3 config generated by Cisco Micro-Tool Generator
! Mode: {mode}
! Date: {now}
! Device: {device}
!
"""
    return header


def generate_snmpv3(user, group, auth_algo, auth_pass, priv_algo, priv_pass, host):
    return f"""
snmp-server view ALL iso included
snmp-server group {group} v3 priv read ALL write ALL
snmp-server user {user} {group} v3 auth {auth_algo} {auth_pass} priv {priv_algo} {priv_pass}
snmp-server host {host} version 3 priv {user}

snmp-server enable traps
"""


def main():
    print("=== SNMPv3 Config Generator v0.3 ===\n")

    mode = choose_mode()
    device = input("Device type (default: Cisco IOS XE): ").strip() or "Cisco IOS XE"
    host = get_non_empty("SNMP manager IP/hostname (trap host): ")

    auth_algo, priv_algo = resolve_algorithms(mode)

    num_users_raw = get_non_empty("How many SNMPv3 users to generate?: ")
    try:
        num_users = int(num_users_raw)
        if num_users < 1:
            raise ValueError
    except ValueError:
        raise ValueError("Number of users must be a positive integer.")

    header = generate_header(mode, device)
    full_output = header

    for i in range(num_users):
        print(f"\n=== User {i+1}/{num_users} ===")
        user = get_non_empty("SNMPv3 username: ")
        default_group = f"{user}_grp"
        group = input(f"Group name [{default_group}]: ").strip() or default_group
        auth_pass = get_non_empty("Auth password: ")
        priv_pass = get_non_empty("Privacy password: ")

        config = generate_snmpv3(
            user=user,
            group=group,
            auth_algo=auth_algo,
            auth_pass=auth_pass,
            priv_algo=priv_algo,
            priv_pass=priv_pass,
            host=host,
        )

        full_output += config + "\n"

    export = input("\nExport to file? (y/n): ").strip().lower()
    if export == "y":
        filename = input("Filename (default: snmpv3_config.txt): ").strip() or "snmpv3_config.txt"
        with open(filename, "w") as f:
            f.write(full_output)
        print(f"\nSaved to file: {filename}\n")
    else:
        print("\nGenerated configuration:\n")
        print(full_output)


if __name__ == "__main__":
    try:
        main()
    except ValueError as e:
        print(f"\n[ERROR] {e}")
        print("Aborting.\n")
